// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['love', 'text!templates/homepage.html'], function(love, template) {
    'use strict';
    var HomepageView;
    return HomepageView = (function(_super) {
      __extends(HomepageView, _super);

      function HomepageView() {
        return HomepageView.__super__.constructor.apply(this, arguments);
      }

      HomepageView.prototype.el = '.main';

      HomepageView.prototype.template = _.template(template);

      HomepageView.prototype.initialize = function(options) {
        return this.render(options);
      };

      HomepageView.prototype.destroy = function() {
        return console.log('destroy');
      };

      HomepageView.prototype.addEventListeners = function() {
        return this.$el.on('click', '[data-project]', this.onClick);
      };

      HomepageView.prototype.render = function(options) {
        this.$el.html(this.template());
        this.addEventListeners();
        if (options.about === true) {
          $('html, body').animate({
            scrollTop: this.$el.find('.about').offset().top
          }, {
            duration: 200,
            specialEasing: 'cubic-bezier(0.165, 0.84, 0.44, 1)'
          });
        } else {
          $('html, body').animate({
            scrollTop: 0
          }, {
            duration: 200,
            specialEasing: 'cubic-bezier(0.165, 0.84, 0.44, 1)'
          });
        }
        return this;
      };

      HomepageView.prototype.lockScroll = function() {
        return console.log('yoooooo');
      };

      HomepageView.prototype.onClick = function(e) {
        var $this;
        e.preventDefault();
        $this = $(this);
        $this.parent().height($(window).height());
        $this.addClass('is-extended').height($(window).height());
        return $('html, body').animate({
          scrollTop: $this.offset().top
        }, {
          duration: 200,
          specialEasing: 'cubic-bezier(0.165, 0.84, 0.44, 1)',
          complete: function() {
            $('html, body').css({
              'overflow': 'hidden',
              'height': '100%'
            });
            $this.addClass('is-fixed');
            love.router.setLoader($this.data('project'));
            return window.setTimeout(function() {
              return console.log('to');
            }, 300);
          }
        });
      };

      return HomepageView;

    })(Backbone.View);
  });

}).call(this);
