// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['love'], function(love) {
    'use strict';
    var NavigationView;
    return NavigationView = (function(_super) {
      __extends(NavigationView, _super);

      function NavigationView() {
        return NavigationView.__super__.constructor.apply(this, arguments);
      }

      NavigationView.prototype.el = '.navigation';

      NavigationView.prototype.header = null;

      NavigationView.prototype.events = {
        'mouseleave': 'onMouseout',
        'click .js-expandNavigation': 'onClick'
      };

      NavigationView.prototype.initialize = function() {
        console.log('initialize');
        this.render();
        return this.addEventListeners();
      };

      NavigationView.prototype.addEventListeners = function() {
        this.$el.on('click', '[data-project]', this.onProjectClick);
        return this.$el.on('click', '.about', this.onAboutClick);
      };

      NavigationView.prototype.onClick = function(e) {
        if (!this.$el.hasClass('is-expanded')) {
          return this.$el.addClass('is-expanded');
        } else {
          return love.router.navigate('', {
            trigger: true
          });
        }
      };

      NavigationView.prototype.onMouseout = function() {
        if (!this.$el.hasClass('js-atBottom')) {
          this.$el.removeClass('is-expanded');
          return this.$el.scrollTop(0);
        }
      };

      NavigationView.prototype.onProjectClick = function(e) {
        var project;
        e.preventDefault();
        project = $(this).data('project');
        return $('html, body').animate({
          scrollTop: 0
        }, {
          duration: 200,
          specialEasing: 'cubic-bezier(0.165, 0.84, 0.44, 1)',
          complete: function() {
            return love.router.navigate(project, {
              trigger: true
            });
          }
        });
      };

      NavigationView.prototype.onAboutClick = function(e) {
        e.preventDefault();
        return love.router.navigate('about', {
          trigger: true
        });
      };

      return NavigationView;

    })(Backbone.View);
  });

}).call(this);
