// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    'use strict';
    var love;
    return love = {
      router: null,
      views: {
        homepage: null,
        projects: {}
      },
      initialize: function() {
        return require(['routers/router'], (function(_this) {
          return function(Router) {
            _this.router = new Router();
            return Backbone.history.start({
              pushState: true,
              root: 'laureboutmy/'
            });
          };
        })(this));
      }
    };
  });

}).call(this);
