// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  require.config({
    shim: {
      underscore: {
        exports: '_'
      },
      backbone: {
        deps: ['jquery', 'underscore'],
        exports: 'Backbone'
      }
    },
    paths: {
      jquery: 'libraries/jquery-1.11.1.min',
      backbone: 'libraries/backbone.min',
      underscore: 'libraries/underscore.min',
      text: 'libraries/require-text.min'
    }
  });

  define(['love'], function(love) {
    return love.initialize();
  });

}).call(this);
