// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['love', 'views/project', 'views/slider', 'text!templates/mediadata.html'], function(L, ProjectView, SliderView, template) {
    'use strict';
    var MediadataView;
    return MediadataView = (function(_super) {
      __extends(MediadataView, _super);

      function MediadataView() {
        return MediadataView.__super__.constructor.apply(this, arguments);
      }

      MediadataView.prototype.template = _.template(template);

      MediadataView.prototype.render = function() {
        $('.navigation').removeClass('js-atBottom');
        this.$el.html(this.template());
        this.addEventListeners();
        this.initializeSlider();
        this.$el.find('article').addClass('is-visible');
        this.$el.addClass('is-visible');
        L.router.unlockScroll();
        return this;
      };

      MediadataView.prototype.addEventListeners = function() {
        return $(window).on('scroll', this.atBottom);
      };

      return MediadataView;

    })(ProjectView);
  });

}).call(this);
